### ISSUE TITLE
Consider overriding previously set options instead of skipping loader configs which already have options

### ISSUE THREAD

**Issue by maoberlehner** [qiyuan-wang/vue-loader-options-plugin#1]
Thank you for making this plugin, this solves my problem of making https://github.com/maoberlehner/node-sass-magic-importer work with Vue / Nuxt.js.

But one thing is making things a little bit more complicated than they have to be (in my opinion): in line https://github.com/qiyuan-wang/vue-loader-options-plugin/blob/master/index.js#L24 you're checking if options already do exist and if so, they are not overwritten by the options provided via the plugin.

Nuxt.js does set options so I have to overwrite the Nuxt.js options, and than set the options with this plugin. This works, but is kinda complicated.

But I think it would make more sense, if options provided via the plugin override all previously set options. What do you think?

I'll make a pull request over the next hours, but feel free to discard it if you think this is not the desired behavior.

Thanks for making this plugin.

**Comment by qiyuan-wang** [comment]
Thank you, @maoberlehner . And I think your solution should be accepted.
